projects:
  app:
    schemaPath: './apollo-server/schema.graphql'
    includes:
      - './src/graphql/*.gql'
      - './src/graphql/*.graphql'
    extensions:
      endpoints:
        default: 'http://localhost:4000/graphql'
